config/routes.rb
Rails.application.routes.draw do
  
  
  
  devise_for :users
  root to: "users#index"
  resources :users
  resources :profiles
  resources :rooms do
    collection do
      get 'search'
      get 'area'
      get 'tokyo'
      get 'oosaka'
      get 'sapporo'
      get 'kyouto'
    end
  end

resources :rooms do
   resource :reservation do
   collection do
  post 'confirm'
        end
      end   
    end

  
resources :reservations, only: [:index]
end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/reservation.rb
class Reservation < ApplicationRecord

belongs_to:room
belongs_to:user


validates :people, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}

validates :start_date, presence: true
validates :end_date, presence:true

validate :start_end_check
validate :date_before_start

def start_end_check
return if start_date.blank? || end_date.blank?
if self.start_date >= self.end_date
errors.add(:end_date, "は開始日以降の日付で選択してください") 
  

end
end


def date_before_start
return if start_date.blank?
errors.add(:start_date, "は今日以降のものを選択してください") if start_date < Date.today
end

def total_date
end_date-start_date
end

def total_price
total_date*room.price*people
end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: %i[ show edit update destroy ]
 

  # GET /reservations or /reservations.json
  def index
    
    @reservations =current_user.reservations
    
        
  end
  # GET /reservations/1 or /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @room = Room.find(params[:room_id])
   @reservation = @room.reservations.new

  end

  def confirm
    @room = Room.find(params[:room_id])
     @reservation = @room.reservations.new(reservation_params)
    

    render :new if @reservation.invalid?
    
end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations or /reservations.json
  def create
    
    
    @reservation =Reservation.new(reservation_params)

  
    
  
    if params[:back] || !@reservation.save
        render :new
    else
        redirect_to action: :index, notice: "予約しました。"
    end
end

  # PATCH/PUT /reservations/1 or /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to reservation_url(@reservation), notice: "予約を編集しました。" }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1 or /reservations/1.json
  def destroy
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url, notice: "予約を削除しました。" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservation
      @reservation = Reservation.find(params[:id])
    end


   
    # Only allow a list of trusted parameters through.
    def reservation_params
      params.require(:reservation).permit(:id,:room_id,:start_date, :end_date, :people,:user_id).merge(user_id:current_user.id)
    end

  
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_with(model: reservation) do |form| %>
  <% if reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
        <% reservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.number_field :room_id %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label :people %>
    <%= form.number_field :people %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reservations/confirm.html.erb
<h1>Confirmation</h1>

<table>
  <thead>
    <tr>
      <th>Room_id</th>
      <th>Start_date</th>
      <th>End_date</th>
      <th>People</th>
      <th>Total_date</th>
      <th>Total_price</th>
      <th>Room_name</th>
     
     

      
      
    </tr>
  </thead>

<td><%= @reservation.room_id%></td>
<td><%= @reservation.start_date%></td>
<td><%= @reservation.end_date%></td>
<td><%= @reservation.people%></td>
<td><%= @reservation.total_date.to_i%></td>
<td><%= @reservation.total_price.to_i%></td>
<td><%= @reservation.room.room_name%></td>
</table>


<%= form_with model: @reservation,url: "/rooms/:room_id/reservation", method: :post, local: true do |f| %>
  <%= f.hidden_field :room_id %>
  <%= f.hidden_field :start_date %>
  <%= f.hidden_field :end_date %>
  <%= f.hidden_field :people %>
  <%= f.hidden_field :total_date %>
  <%= f.hidden_field :total_price %>
  <%= f.hidden_field :room_name %>
  <%= f.hidden_field :user_id %>
  <%= f.submit "確定" %>
  
<% end %>

<%= link_to 'Back', new_room_reservation_path %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      
      <th>Room_image</th>
      <th>Room_name</th>
      <th>Introduce</th>
      <th>Total_price</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Created_at</th>
      

      
      
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
      <tr>
       
        
        <% if reservation.room.room_image? %>
  <td><%= image_tag reservation.room.room_image.url %></td>
<% else %>
  <td><%= image_tag ("room.png"),:size =>'75x50' %></td>
<% end %>
        <td><%= reservation.room.room_name%></td>
        <td><%= reservation.room.introduce%></td>
        <td><%= reservation.total_price.to_i%></td>
        <td><%= reservation.start_date %></td>
        <td><%= reservation.end_date %></td>
        <td><%= reservation.created_at %></td>
        
        

       
    <% end %>
    </tbody>

    </tbody>
    </table>
    
<%= link_to 'Back', users_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>
<%= form_with model: @reservation , url:confirm_room_reservation_path,local:true do |f| %>
    <% if @reservation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>
  
        <ul>
          <% @reservation.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    
  
    <div class="field">
      <%= f.label :start_date %>
      <%= f.date_select :start_date %>
    </div>
  
    <div class="field">
      <%= f.label :end_date %>
      <%= f.date_select :end_date %>
    </div>
  
    <div class="field">
      <%= f.label :people %>
      <%= f.number_field :people %>
    </div>
  
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>
  <%= link_to 'Back', room_path(@room) %>
  

  

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room:</strong>
  <%= @reservation.room_id %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @reservation.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @reservation.end_date %>
</p>

<p>
  <strong>People:</strong>
  <%= @reservation.people %>
</p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>