config/routes.rb
Rails.application.routes.draw do
  
  
  
  devise_for :users
  root to: "users#index"
  resources :users
  resources :profiles
  resources :rooms do
    collection do
      get 'search'
      get 'area'
      get 'tokyo'
      get 'oosaka'
      get 'sapporo'
      get 'kyouto'
    end
  end

resources :rooms do
   resource :reservation do
   collection do
  post 'confirm'
        end
      end   
    end

  
resources :reservations, only: [:index]
end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/room.rb
class Room < ApplicationRecord

  mount_uploader :room_image, RoomImageUploader

  belongs_to :user
  has_many :reservations

    validates :price, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
    validates :room_name, presence: true
    validates :introduce, presence: true
    validates :address, presence: true
    


    def self.search(search)
      return Room.all unless search
      Room.where(['room_name LIKE ?', "%#{search}%"]).or Room.where(['introduce LIKE ?', "%#{search}%"])
    end

    def self.area(area)
      return Room.all unless area
  Room.where(['address LIKE ?', "%#{area}%"])
 
    end

    def self.tokyo(tokyo)
      return Room.all unless tokyo
  Room.where(['address LIKE ?', "%#{tokyo}%"])
 
    end 


  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms= current_user.rooms
  
   
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)
    @room.user_id =current_user.id
   
    respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_url(@room), notice: "部屋を作成しました。" }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to room_url(@room), notice: "部屋を更新しました。" }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "部屋を削除しました。" }
      format.json { head :no_content }
    end
  end

  def search
          #Viewのformで取得したパラメータをモデルに渡す
      @rooms = Room.search(params[:search])
    @room_total = @rooms.count
  end

  def area
    #Viewのformで取得したパラメータをモデルに渡す
@rooms = Room.area(params[:area])
@room_total = @rooms.count
end

def tokyo
  
  @rooms = Room.where(address:"東京")
  @room_total = @rooms.count
end

def oosaka
  
  @rooms = Room.where(address:"大阪")
  @room_total = @rooms.count
end


def sapporo
  
  @rooms = Room.where(address:"札幌")
  @room_total = @rooms.count
end


def kyouto
  
  @rooms = Room.where(address:"京都")
  @room_total = @rooms.count
end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
      
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:user_id, :room_image, :room_name, :introduce, :price, :address,:id)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
 
  
</div>
  <div class="field">
  <%= form.label :room_image %>
  <%= form.file_field :room_image %>
</div>

  <div class="field">
    <%= form.label :room_name %>
    <%= form.text_field :room_name %>
  </div>

  <div class="field">
    <%= form.label :introduce %>
    <%= form.text_field :introduce %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/area.html.erb
<p>エリア検索</p>
<%= form_tag(area_rooms_path,:method => 'get') do %>
  <%= text_field_tag :area %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>
    <h1>Rooms</h1>

    <table>
      <thead>
        <tr>
          <th>User</th>
          <th>Room image</th>
          <th>Room name</th>
          <th>Introduce</th>
          <th>Price</th>
          <th>Address</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td><%= room.user_id %></td>
            <% if room.room_image? %>
  <td><%= image_tag room.room_image.url %></td>
<% else %>
  <td><%= image_tag ("room.png"),:size =>'75x50' %></td>
  <% end %>
            <td><%= link_to room.room_name, room %></td>
            <td><%= room.introduce %></td>
            <td><%= room.price %></td>
            <td><%= room.address %></td>
           
            <td><%= link_to 'Edit', edit_room_path(room) %></td>
            <td><%= button_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <br>
    <p>合計数: <%= @room_total %></p>
       
    <%= link_to 'New Room', new_room_path %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>




<table>
  <thead>
    <tr>
      
      <th>Room image</th>
      <th>Room name</th>
      <th>Introduce</th>
      <th>Price</th>
      <th>Address</th>
      
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        
        <% if room.room_image? %>
  <td><%= image_tag room.room_image.url %></td>
<% else %>
  <td><%= image_tag ("room.png"),:size =>'75x50' %></td>
<% end %>
        <td><%= link_to room.room_name, room %></td>
        <td><%= room.introduce %></td>
        <td><%= room.price %></td>
        <td><%= room.address %></td>
       
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= button_to'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/kyouto.html.erb
<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Room image</th>
      <th>Room name</th>
      <th>Introduce</th>
      <th>Price</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.user_id %></td>
        <% if room.room_image? %>
        <td><%= image_tag room.room_image.url %></td>
      <% else %>
        <td><%= image_tag ("room.png"),:size =>'75x50' %></td>
        <% end %>
        <td><%= link_to room.room_name, room %></td>
        <td><%= room.introduce %></td>
        <td><%= room.price %></td>
        <td><%= room.address %></td>
       
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= button_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p>合計数: <%= @room_total %></p>
   
<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/oosaka.html.erb
<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Room image</th>
      <th>Room name</th>
      <th>Introduce</th>
      <th>Price</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.user_id %></td>
        <% if room.room_image? %>
        <td><%= image_tag room.room_image.url %></td>
      <% else %>
        <td><%= image_tag ("room.png"),:size =>'75x50' %></td>
        <% end %>
        <td><%= link_to room.room_name, room %></td>
        <td><%= room.introduce %></td>
        <td><%= room.price %></td>
        <td><%= room.address %></td>
       
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= button_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p>合計数: <%= @room_total %></p>
   
<%= link_to 'New Room', new_room_path %>

app/views/rooms/sapporo.html.erb
<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Room image</th>
      <th>Room name</th>
      <th>Introduce</th>
      <th>Price</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.user_id %></td>
        <% if room.room_image? %>
        <td><%= image_tag room.room_image.url %></td>
      <% else %>
        <td><%= image_tag ("room.png"),:size =>'75x50' %></td>
        <% end %>
        <td><%= link_to room.room_name, room %></td>
        <td><%= room.introduce %></td>
        <td><%= room.price %></td>
        <td><%= room.address %></td>
       
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= button_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p>合計数: <%= @room_total %></p>
   
<%= link_to 'New Room', new_room_path %>

app/views/rooms/search.html.erb
<p>フリーワード検索</p>
<%= form_tag(search_rooms_path,:method => 'get') do %>
  <%= text_field_tag :search %>
  <%= submit_tag 'Search', :name => nil %>
<% end %>


    <h1>Rooms</h1>

    <table>
      <thead>
        <tr>
          <th>User</th>
          <th>Room image</th>
          <th>Room name</th>
          <th>Introduce</th>
          <th>Price</th>
          <th>Address</th>
          <th colspan="3"></th>
        </tr>
      </thead>
    
      <tbody>
        <% @rooms.each do |room| %>
          <tr>
            <td><%= room.user_id %></td>
            <% if room.room_image? %>
            <td><%= image_tag room.room_image.url %></td>
          <% else %>
            <td><%= image_tag ("room.png"),:size =>'75x50' %></td>
            <% end %>
            <td><%= link_to room.room_name, room %></td>
            <td><%= room.introduce %></td>
            <td><%= room.price %></td>
            <td><%= room.address %></td>
           
            <td><%= link_to 'Edit', edit_room_path(room) %></td>
            <td><%= button_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    
    <br>
    <p>合計数: <%= @room_total %></p>
       
    <%= link_to 'New Room', new_room_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @room.user_id %>
</p>

<p>
  <strong>Room_id:</strong>
  <%= @room.id %>
</p>


<p>
  <strong>Room image:</strong>
  <%= @room.room_image %>
</p>

<p>
  <strong>Room name:</strong>
  <%= @room.room_name %>
</p>

<p>
  <strong>Introduce:</strong>
  <%= @room.introduce %>
</p>

<p>
  <strong>Price:</strong>
  <%= @room.price %>
</p>

<p>
  <strong>Address:</strong>
  <%= @room.address %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<td><%= link_to '予約',new_room_reservation_path(@room) %></td>
<%= link_to 'Back', rooms_path %>

app/views/rooms/tokyo.html.erb
<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Room image</th>
      <th>Room name</th>
      <th>Introduce</th>
      <th>Price</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.user_id %></td>
        <% if room.room_image? %>
        <td><%= image_tag room.room_image.url %></td>
      <% else %>
        <td><%= image_tag ("room.png"),:size =>'75x50' %></td>
        <% end %>
        <td><%= link_to room.room_name, room %></td>
        <td><%= room.introduce %></td>
        <td><%= room.price %></td>
        <td><%= room.address %></td>
       
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= button_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<p>合計数: <%= @room_total %></p>
   
<%= link_to 'New Room', new_room_path %>